use latest version of node (11.x) in Travis
With 7.9.0 we're getting this error in the Travis build:
TypeError: util_1.promisify is not a function

util.promisify was introduced in Node 8.X version.